// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

public partial class ControleProduto
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    public int IdProduto { get; set; }

    [Column("entrada", TypeName = "datetime")]
    public DateTime Entrada { get; set; }

    [Column("saida", TypeName = "datetime")]
    public DateTime Saida { get; set; }

    [ForeignKey("IdProduto")]
    [InverseProperty("ControleProduto")]
    public virtual Produtos IdProdutoNavigation { get; set; }
}