// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

public partial class dbControleContext : DbContext
{
    public dbControleContext()
    {
      
    }

    public dbControleContext(DbContextOptions<dbControleContext> options)
        : base(options)
    {
        Database.EnsureCreated();

    }

    public virtual DbSet<ControleProduto> ControleProduto { get; set; }

    public virtual DbSet<Fornecedores> Fornecedores { get; set; }

    public virtual DbSet<Produtos> Produtos { get; set; }

    public virtual DbSet<Servicos> Servicos { get; set; }

    public virtual DbSet<Usuarios> Usuarios { get; set; }

    public virtual DbSet<VwServicoFornecedor> VwServicoFornecedor { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {

            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();

            optionsBuilder.UseSqlServer(configuration.GetConnectionString("SolicitaCompraContextConnection"));
        }
    }



      

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ControleProduto>(entity =>
        {
            entity.HasOne(d => d.IdProdutoNavigation).WithMany(p => p.ControleProduto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ControleProdutos");
        });

        modelBuilder.Entity<Servicos>(entity =>
        {
            entity.HasOne(d => d.IdFornecedorNavigation).WithMany(p => p.Servicos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServicosFornecedores");
        });

        modelBuilder.Entity<VwServicoFornecedor>(entity =>
        {
            entity.ToView("VW_ServicoFornecedor");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}