// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

public partial class Fornecedores
{
    [Key]
    [Column("ID")]
    [Display(Name = "Código do Fornecedor")]
    public int Id { get; set; }

    
    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Nome Completo", Description = "Nome e Sobrenome.")]
    [Required(ErrorMessage = "O nome completo é obrigatório.")]
    [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage =
            "Números e caracteres especiais não são permitidos no nome.")]
    public string Nome { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [Column("CEP")]
    [StringLength(10)]
    [Unicode(false)]
    public string Cep { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(60)]
    [Unicode(false)]
    public string Rua { get; set; }

    [StringLength(60)]
    [Unicode(false)]
    public string Numero { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(60)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(60)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(60)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Column(TypeName = "text")]
    public string Complemento { get; set; }


    [Required(ErrorMessage = "Informe o seu email")]
    [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido...")]
    [StringLength(70)]
    [Unicode(false)]
    [Display(Name = "E-mail")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [Column("CNPJ")]
    [StringLength(20)]
    [Unicode(false)]
    [Display(Name = "CNPJ")]
    public string Cnpj { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(20)]
    [Unicode(false)]
    [Display(Name = "Inscrição Estadual")]
    public string IncricaoEstadual { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(20)]
    [Unicode(false)]
    [Display(Name = "Inscrição Municipal")]
    public string IncricaoMunicipal { get; set; }

    [InverseProperty("IdFornecedorNavigation")]
    [Display(Name = "Código do Fornecedor")]
    public virtual ICollection<Servicos> Servicos { get; set; } = new List<Servicos>();
}