// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

public partial class Produtos
{
    [Key]
    [Column("ID")]
    [Display(Name = "Código do Produto")]
    public int Id { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(100)]
    [Unicode(false)]
    public string Produto { get; set; }

    
    [Unicode(false)]
    [Required(ErrorMessage = "Campo obrigatório.")]
    [Display(Name = "Descrição")]
    public string Descricao { get; set; }



    [Display(Name = "Código EAN")]
    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(20)]
    [Unicode(false)]
    public string Codigo { get; set; }

    [Column(TypeName = "money")]
    [Display(Name = "Preço por Unidade")]
    public decimal ValorQtd { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Quantidade Mínima para Estoque")]
    public string QtdMin { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Quantidade  do Estoque")]
    public string QtdEstoque { get; set; }


    [InverseProperty("IdProdutoNavigation")]
    [Display(Name = "Código do Fornecedor")]

    public virtual ICollection<ControleProduto> ControleProduto { get; set; } = new List<ControleProduto>();
}