// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

public partial class Servicos
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }


    [Display(Name = "Código do Fornecedor")]
    public int IdFornecedor { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [Column("servico")]
    [StringLength(80)]
    [Unicode(false)]
    [Display(Name = "Serviço")]
    public string Servico { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [Column("descricao")]
    [Display(Name = "Descricão")]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("prazo", TypeName = "datetime")]
    [Display(Name = "Prazo Padrão")]
    public DateTime Prazo { get; set; }

    [ForeignKey("IdFornecedor")]
    [InverseProperty("Servicos")]

    public virtual Fornecedores IdFornecedorNavigation { get; set; }
}