// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

public partial class Usuarios
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }


    [StringLength(100)]
    [Unicode(false)]
    [Display(Name = "Nome Completo", Description = "Nome e Sobrenome.")]
    [Required(ErrorMessage = "O nome completo é obrigatório.")]
    [RegularExpression(@"^[a-zA-Z''-'\s]{1,40}$", ErrorMessage =
            "Números e caracteres especiais não são permitidos no nome.")]
    public string Nome { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(100)]
    [Unicode(false)]
    public string Departamento { get; set; }

    [Required(ErrorMessage = "Campo obrigatório.")]
    [StringLength(20)]
    [Unicode(false)]
    [Display(Name = "Matrícula")]
    public string Matricula { get; set; }


    [Required(ErrorMessage = "Informe o seu email")]
    [RegularExpression(".+\\@.+\\..+", ErrorMessage = "Informe um email válido...")]
    [StringLength(70)]
    [Unicode(false)]
    public string Email { get; set; }
}