// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SolicitaCompra.Models;

[Keyless]
public partial class VwServicoFornecedor
{
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("servico")]
    [StringLength(80)]
    [Unicode(false)]
    public string Servico { get; set; }

    [Required]
    [Column("descricao")]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("prazo", TypeName = "datetime")]
    public DateTime Prazo { get; set; }
}